image: node:12.18.4
pipelines:
  branches:
    release/rtm:
      - step:
          name: deployment
          caches:
            - node
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $DEPLOY_USER
                SERVER: $DEPLOY_HOST_RTM
                COMMAND: 'deploy-rtm.sh'
                MODE: 'script'
    master:
      - step:
          name: deployment
          deployment: production
          script:
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: $DEPLOY_USER
              SERVER: $DEPLOY_HOST
              COMMAND: 'deploy.sh'
              MODE: 'script'